export interface SectorWeights {
  severity: number;
  asset_importance: number;
  affected_users: number;
  data_sensitivity: number;
  attack_confidence: number;
  business_impact: number;
}

export interface ThreatDefinition {
  id: string;
  title: string;
  severity: number; // 1-5 scale
  assetImportance: number; // 1-5 scale
  affectedUsers: number; // count
  dataSensitivity: number; // 1-5 scale
  attackConfidence: number; // 0.0 - 1.0
  businessImpact: number; // 1-5 scale
  affectedAssets: string[];
  affectedUsersList: string[];
  attackTypes: string[];
  mitreTechniques: string[];
  story: string;
  playbook: string;
}

export interface SectorProfile {
  id: string;
  name: string;
  description: string;
  emphasis: string[];
  defaultVersion: string;
  weights: SectorWeights;
  threats: ThreatDefinition[];
}

export const SECTOR_PROFILES: Record<string, SectorProfile> = {
  healthcare: {
    id: 'healthcare',
    name: 'Healthcare',
    description: 'Patient safety, PHI and clinical systems focused',
    emphasis: [
      'Patient Safety',
      'Protected Health Information (PHI)',
      'Clinical Systems',
      'Medical Devices',
      'Regulatory Compliance',
    ],
    defaultVersion: 'weighted-v1-healthcare',
    weights: {
      severity: 0.25,
      asset_importance: 0.15,
      affected_users: 0.15,
      data_sensitivity: 0.25,
      attack_confidence: 0.10,
      business_impact: 0.10,
    },
    threats: [
      {
        id: 'INC-HC-001',
        title: 'Ransomware Against EHR',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 4,
        dataSensitivity: 5,
        attackConfidence: 0.95,
        businessImpact: 5,
        affectedAssets: ['EHR-CORE-DB01', 'ICU-TELEMETRY-HUB'],
        affectedUsersList: ['ehr_sysadmin', 'dr_chen_chief', 'nurse_sarah_icu', 'telemed_patient_ops'],
        attackTypes: ['Ransomware Execution', 'Shadow Copy Deletion', 'EHR Interruption'],
        mitreTechniques: ['T1486: Data Encrypted for Impact', 'T1490: Inhibit System Recovery'],
        story: 'Sophisticated ransomware deployed against primary electronic health records database, threatening hospital-wide clinical admissions.',
        playbook: 'Clinical EHR Isolation & Cold Backup Restoration',
      },
      {
        id: 'INC-HC-002',
        title: 'Medical Device Compromise',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 2,
        dataSensitivity: 3,
        attackConfidence: 0.90,
        businessImpact: 5,
        affectedAssets: ['ICU-TELEMETRY-HUB', 'PHARM-DISPENSE-01'],
        affectedUsersList: ['nurse_sarah_icu', 'dr_chen_chief'],
        attackTypes: ['Firmware Tampering', 'Man-in-the-Middle Telemetry'],
        mitreTechniques: ['T1565: Data Manipulation', 'T1199: Trusted Relationship Abuse'],
        story: 'Unauthorized firmware downgrade and anomaly detected in ICU infusion telemetry stream, risking real-time dosing inaccuracies.',
        playbook: 'Medical Device VLAN Quarantine & Manual Failover',
      },
      {
        id: 'INC-HC-003',
        title: 'Patient Data Exfiltration',
        severity: 4,
        assetImportance: 4,
        affectedUsers: 5,
        dataSensitivity: 5,
        attackConfidence: 0.85,
        businessImpact: 4,
        affectedAssets: ['PACS-IMAGING-SRV', 'EHR-CORE-DB01'],
        affectedUsersList: ['radiology_tech_bob', 'ehr_sysadmin', 'nurse_sarah_icu', 'dr_chen_chief', 'telemed_patient_ops'],
        attackTypes: ['HIPAA Data Exfiltration', 'Mass DICOM Export'],
        mitreTechniques: ['T1048: Exfiltration Over Alternative Protocol', 'T1005: Data from Local System'],
        story: 'Over 45,000 patient diagnostic scans and medical histories staged to an unauthorized external IP via encrypted DICOM tunnel.',
        playbook: 'HIPAA Breach Containment & Forensic IP Block',
      },
      {
        id: 'INC-HC-004',
        title: 'Healthcare Phishing Campaign',
        severity: 3,
        assetImportance: 3,
        affectedUsers: 5,
        dataSensitivity: 4,
        attackConfidence: 0.90,
        businessImpact: 3,
        affectedAssets: ['NURSE-STATION-4B'],
        affectedUsersList: ['nurse_sarah_icu', 'telemed_patient_ops', 'radiology_tech_bob', 'dr_chen_chief', 'ehr_sysadmin'],
        attackTypes: ['Spear Phishing', 'Credential Harvesting'],
        mitreTechniques: ['T1566: Phishing', 'T1056: Input Capture'],
        story: 'Targeted clinical staff email campaign spoofing Hospital Accreditation Board credential portal, capturing 5 clinical sessions.',
        playbook: 'Emergency Password Reset & Inbound Domain Block',
      },
      {
        id: 'INC-HC-005',
        title: 'Clinical System Availability Attack',
        severity: 4,
        assetImportance: 5,
        affectedUsers: 4,
        dataSensitivity: 3,
        attackConfidence: 0.80,
        businessImpact: 4,
        affectedAssets: ['PHARM-DISPENSE-01', 'NURSE-STATION-4B'],
        affectedUsersList: ['nurse_sarah_icu', 'ehr_sysadmin', 'dr_chen_chief', 'telemed_patient_ops'],
        attackTypes: ['Denial of Service', 'SYN Flood on Clinical Dispatch'],
        mitreTechniques: ['T1498: Network Denial of Service', 'T1499: Endpoint DoS'],
        story: 'Distributed SYN flood exhausting automated medication dispenser network interfaces, delaying scheduled ICU pharmaceutical rounds.',
        playbook: 'Anti-DDoS Scrubbing & Emergency Manual Dispatch',
      },
      {
        id: 'INC-HC-006',
        title: 'Telemedicine Account Takeover',
        severity: 3,
        assetImportance: 3,
        affectedUsers: 3,
        dataSensitivity: 4,
        attackConfidence: 0.85,
        businessImpact: 2,
        affectedAssets: ['TELEMED-PORTAL-01'],
        affectedUsersList: ['telemed_patient_ops', 'dr_chen_chief', 'nurse_sarah_icu'],
        attackTypes: ['Session Hijacking', 'Unauthorized Telehealth Access'],
        mitreTechniques: ['T1539: Steal Web Session Cookie', 'T1078: Valid Accounts'],
        story: 'Attacker hijacked doctor virtual consultation tokens from an unmanaged residence laptop, attempting prescription modification.',
        playbook: 'Session Revocation & Ephemeral Token Purge',
      },
    ],
  },
  banking: {
    id: 'banking',
    name: 'Banking',
    description: 'Financial systems, transaction integrity and fraud focused',
    emphasis: [
      'Financial Systems',
      'Transaction Integrity',
      'Fraud Prevention',
      'High-Value Assets',
      'Payment Infrastructure',
    ],
    defaultVersion: 'weighted-v1-banking',
    weights: {
      severity: 0.25,
      asset_importance: 0.20,
      affected_users: 0.10,
      data_sensitivity: 0.20,
      attack_confidence: 0.15,
      business_impact: 0.10,
    },
    threats: [
      {
        id: 'INC-BK-001',
        title: 'Payment API Attack',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 3,
        dataSensitivity: 5,
        attackConfidence: 0.95,
        businessImpact: 5,
        affectedAssets: ['PAYMENT-API-GW01', 'CORE-BANKING-LEDGER'],
        affectedUsersList: ['payment_api_engineer', 'core_dba_admin', 'swift_operator_lead'],
        attackTypes: ['API Parameter Injection', 'Transaction Tampering'],
        mitreTechniques: ['T1190: Exploit Public-Facing Application', 'T1059: Command Execution'],
        story: 'High-velocity token replay and parameter manipulation targeting ISO-20022 payment API, forging card authorization responses.',
        playbook: 'Payment Gateway Hard Isolation & HSM Re-Keying',
      },
      {
        id: 'INC-BK-002',
        title: 'Account Takeover',
        severity: 4,
        assetImportance: 4,
        affectedUsers: 5,
        dataSensitivity: 5,
        attackConfidence: 0.90,
        businessImpact: 4,
        affectedAssets: ['ONLINE-BANKING-WEB', 'CORE-BANKING-LEDGER'],
        affectedUsersList: ['retail_fraud_analyst', 'payment_api_engineer', 'core_dba_admin', 'swift_operator_lead'],
        attackTypes: ['MFA Fatigue', 'Session Hijacking', 'Beneficiary Addition'],
        mitreTechniques: ['T1539: Steal Web Session Cookie', 'T1110: Brute Force'],
        story: 'Synchronized takeover of 30+ high-net-worth commercial banking accounts following residential MFA push fatigue attacks.',
        playbook: 'Commercial Account Freeze & Immediate Out-of-Band Callout',
      },
      {
        id: 'INC-BK-003',
        title: 'Wire Transfer Fraud',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 2,
        dataSensitivity: 4,
        attackConfidence: 0.88,
        businessImpact: 5,
        affectedAssets: ['SWIFT-ALLIANCE-GATE', 'CORE-BANKING-LEDGER'],
        affectedUsersList: ['swift_operator_lead', 'core_dba_admin'],
        attackTypes: ['Unauthorized Wire Injection', 'Operator Bypass'],
        mitreTechniques: ['T1078: Valid Accounts', 'T1565: Data Manipulation'],
        story: 'Unauthorized $12.4M outgoing international settlement messages queued during non-operating hours using compromised dual-authorization certificates.',
        playbook: 'SWIFT Alliance Kill-Switch & Central Clearing Revocation',
      },
      {
        id: 'INC-BK-004',
        title: 'Credential Stuffing Against Online Banking',
        severity: 4,
        assetImportance: 4,
        affectedUsers: 5,
        dataSensitivity: 4,
        attackConfidence: 0.92,
        businessImpact: 3,
        affectedAssets: ['ONLINE-BANKING-WEB'],
        affectedUsersList: ['retail_fraud_analyst', 'payment_api_engineer', 'core_dba_admin'],
        attackTypes: ['Credential Stuffing', 'Distributed Botnet Proxying'],
        mitreTechniques: ['T1110.004: Credential Stuffing', 'T1090: Proxy'],
        story: 'Over 2.8 million automated credential stuffing attempts through residential proxies hitting customer login endpoints with a 1.2% success hit rate.',
        playbook: 'Cloudflare WAF Bot Fight Mode & Forced Password Rotations',
      },
      {
        id: 'INC-BK-005',
        title: 'Banking Data Exfiltration',
        severity: 4,
        assetImportance: 5,
        affectedUsers: 4,
        dataSensitivity: 5,
        attackConfidence: 0.85,
        businessImpact: 4,
        affectedAssets: ['CORE-BANKING-LEDGER', 'AML-FRAUD-ANALYTICS'],
        affectedUsersList: ['core_dba_admin', 'retail_fraud_analyst', 'payment_api_engineer', 'swift_operator_lead'],
        attackTypes: ['SQL Query Exfiltration', 'Encrypted Tunneling'],
        mitreTechniques: ['T1005: Data from Local System', 'T1048: Exfiltration'],
        story: 'Suspicious large-scale SQL query dumps of cardholder PANs and IBANs transferred via encrypted SSH tunnel from replica database node.',
        playbook: 'PCI-DSS Data Leakage Containment & Database Firewall Lock',
      },
      {
        id: 'INC-BK-006',
        title: 'Payment Infrastructure Attack',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 4,
        dataSensitivity: 4,
        attackConfidence: 0.90,
        businessImpact: 5,
        affectedAssets: ['PAYMENT-API-GW01', 'ATM-SWITCH-DIRECTOR'],
        affectedUsersList: ['payment_api_engineer', 'core_dba_admin', 'swift_operator_lead', 'retail_fraud_analyst'],
        attackTypes: ['Hardware Security Module Disruption', 'Infrastructure DoS'],
        mitreTechniques: ['T1499: Endpoint Denial of Service', 'T1489: Service Stop'],
        story: 'Repeated cryptographic fault injection attempts targeting the primary HSM cluster, threatening core payment settlement failovers.',
        playbook: 'Failover to Disaster Recovery Settlement Cluster',
      },
      {
        id: 'INC-BK-007',
        title: 'ATM Malware',
        severity: 4,
        assetImportance: 4,
        affectedUsers: 2,
        dataSensitivity: 2,
        attackConfidence: 0.80,
        businessImpact: 3,
        affectedAssets: ['ATM-SWITCH-DIRECTOR'],
        affectedUsersList: ['retail_fraud_analyst', 'core_dba_admin'],
        attackTypes: ['ATM Jackpotting Malware', 'XFS Subsystem Hooking'],
        mitreTechniques: ['T1055: Process Injection', 'T1562: Impair Defenses'],
        story: 'C&C beaconing and XFS API manipulation detected across 14 metropolitan branch ATM controllers attempting cash jackpotting command triggers.',
        playbook: 'ATM Dispenser Bus Disconnect & Fleet Firmware Verification',
      },
    ],
  },
  ecommerce: {
    id: 'ecommerce',
    name: 'E-Commerce',
    description: 'Customer accounts, checkout availability and transaction protection',
    emphasis: [
      'Customer Accounts',
      'Payment Gateway',
      'Checkout Availability',
      'Customer PII',
      'Revenue Protection',
    ],
    defaultVersion: 'weighted-v1-ecommerce',
    weights: {
      severity: 0.20,
      asset_importance: 0.15,
      affected_users: 0.20,
      data_sensitivity: 0.15,
      attack_confidence: 0.15,
      business_impact: 0.15,
    },
    threats: [
      {
        id: 'INC-EC-001',
        title: 'Payment Gateway Attack',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 4,
        dataSensitivity: 5,
        attackConfidence: 0.95,
        businessImpact: 5,
        affectedAssets: ['PAYMENT-STRIPE-PROXY', 'CHECKOUT-SERVICE-PROD'],
        affectedUsersList: ['lead_checkout_dev', 'secops_analyst_ec', 'fulfillment_ops_manager', 'customer_support_lead'],
        attackTypes: ['Magecart Web Skimmer', 'Formjacking'],
        mitreTechniques: ['T1059.007: JavaScript Insertion', 'T1056: Input Capture'],
        story: 'Obfuscated JavaScript skimmer injected into production checkout bundle via compromised third-party analytics script tag.',
        playbook: 'CDN Bundle Rollback & Subresource Integrity Enforcement',
      },
      {
        id: 'INC-EC-002',
        title: 'Checkout API Abuse',
        severity: 4,
        assetImportance: 5,
        affectedUsers: 5,
        dataSensitivity: 4,
        attackConfidence: 0.92,
        businessImpact: 5,
        affectedAssets: ['CHECKOUT-SERVICE-PROD', 'INVENTORY-DB-CLUSTER'],
        affectedUsersList: ['lead_checkout_dev', 'fulfillment_ops_manager', 'secops_analyst_ec', 'customer_support_lead'],
        attackTypes: ['Race Condition Exploit', 'Negative Price Order Injection'],
        mitreTechniques: ['T1190: Exploit Public-Facing Application', 'T1068: Privilege Escalation'],
        story: 'Adversary exploiting concurrency lock race condition in coupon application logic, draining $340k in promotional credit.',
        playbook: 'Rate Limiting Ingress Rules & Idempotency Key Lock',
      },
      {
        id: 'INC-EC-003',
        title: 'Customer Account Takeover',
        severity: 4,
        assetImportance: 3,
        affectedUsers: 5,
        dataSensitivity: 4,
        attackConfidence: 0.90,
        businessImpact: 4,
        affectedAssets: ['CUSTOMER-AUTH-IAM'],
        affectedUsersList: ['customer_support_lead', 'lead_checkout_dev', 'secops_analyst_ec', 'fulfillment_ops_manager'],
        attackTypes: ['Credential Stuffing', 'Loyalty Point Draining'],
        mitreTechniques: ['T1110.004: Credential Stuffing', 'T1539: Steal Web Session Cookie'],
        story: 'Coordinated bot network brute-forcing customer profiles, re-routing saved shipping addresses, and depleting reward points on luxury items.',
        playbook: 'Revoke Customer Tokens & Enable Mandatory CAPTCHA',
      },
      {
        id: 'INC-EC-004',
        title: 'Customer PII Exposure',
        severity: 4,
        assetImportance: 4,
        affectedUsers: 5,
        dataSensitivity: 5,
        attackConfidence: 0.85,
        businessImpact: 4,
        affectedAssets: ['CUSTOMER-AUTH-IAM', 'INVENTORY-DB-CLUSTER'],
        affectedUsersList: ['lead_checkout_dev', 'secops_analyst_ec', 'customer_support_lead', 'fulfillment_ops_manager'],
        attackTypes: ['IDOR Vulnerability', 'Bulk PII Scraping'],
        mitreTechniques: ['T1005: Data from Local System', 'T1552: Unsecured Credentials'],
        story: 'Broken object-level authorization on order tracking endpoint allowing unauthenticated scraping of customer phone numbers and home addresses.',
        playbook: 'API Route Hotfix & Perimeter Web Application Firewall Rule',
      },
      {
        id: 'INC-EC-005',
        title: 'E-Commerce Ransomware',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 4,
        dataSensitivity: 4,
        attackConfidence: 0.90,
        businessImpact: 5,
        affectedAssets: ['INVENTORY-DB-CLUSTER', 'CHECKOUT-SERVICE-PROD'],
        affectedUsersList: ['fulfillment_ops_manager', 'lead_checkout_dev', 'secops_analyst_ec'],
        attackTypes: ['Database Encryption', 'Fulfillment Lockout'],
        mitreTechniques: ['T1486: Data Encrypted for Impact', 'T1489: Service Stop'],
        story: 'Ransomware encryption targeting warehouse relational database volumes, halting package labeling and same-day delivery dispatch.',
        playbook: 'Failover to Multi-Region Read Replica & Read-Only Store Mode',
      },
      {
        id: 'INC-EC-006',
        title: 'Bot-Based Inventory Abuse',
        severity: 3,
        assetImportance: 4,
        affectedUsers: 3,
        dataSensitivity: 2,
        attackConfidence: 0.85,
        businessImpact: 4,
        affectedAssets: ['CHECKOUT-SERVICE-PROD', 'ELASTIC-CATALOG-SEARCH'],
        affectedUsersList: ['lead_checkout_dev', 'fulfillment_ops_manager', 'customer_support_lead'],
        attackTypes: ['Scalping Bot Automation', 'Cart Hoarding Denial of Inventory'],
        mitreTechniques: ['T1499: Endpoint DoS', 'T1071: Application Layer Protocol'],
        story: 'Automated scalping bots holding 18,000 limited-edition units in temporary checkout reservations, blocking genuine consumers.',
        playbook: 'Cart Reservation Expiration Clamp & Device Fingerprint Throttling',
      },
      {
        id: 'INC-EC-007',
        title: 'Credential Stuffing',
        severity: 3,
        assetImportance: 3,
        affectedUsers: 5,
        dataSensitivity: 3,
        attackConfidence: 0.88,
        businessImpact: 3,
        affectedAssets: ['CUSTOMER-AUTH-IAM'],
        affectedUsersList: ['customer_support_lead', 'lead_checkout_dev', 'secops_analyst_ec'],
        attackTypes: ['High-Volume Login Testing', 'Proxy Rotation'],
        mitreTechniques: ['T1110.004: Credential Stuffing'],
        story: 'Distributed credential stuffing barrage testing breached combo lists against checkout customer login gateways.',
        playbook: 'Geographic IP Anomaly Blocking & Rate Limiting',
      },
    ],
  },
  saas: {
    id: 'saas',
    name: 'SaaS / Technology',
    description: 'Cloud infrastructure, tenant isolation, APIs and supply chain security',
    emphasis: [
      'Cloud Infrastructure',
      'Tenant Isolation',
      'API Security',
      'Secrets Protection',
      'Software Supply Chain',
    ],
    defaultVersion: 'weighted-v1-saas',
    weights: {
      severity: 0.20,
      asset_importance: 0.20,
      affected_users: 0.15,
      data_sensitivity: 0.15,
      attack_confidence: 0.15,
      business_impact: 0.15,
    },
    threats: [
      {
        id: 'INC-SAAS-001',
        title: 'Tenant Isolation Failure',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 5,
        dataSensitivity: 5,
        attackConfidence: 0.95,
        businessImpact: 5,
        affectedAssets: ['AURORA-MULTITENANT-DB', 'K8S-PROD-EKS-CLUSTER'],
        affectedUsersList: ['platform_lead_sre', 'backend_api_dev', 'iam_security_architect', 'devops_build_bot'],
        attackTypes: ['Tenant Boundary Escape', 'Cross-Org Query Leak'],
        mitreTechniques: ['T1190: Exploit Public-Facing Application', 'T1005: Data from Local System'],
        story: 'Flaw in row-level security policy engine allowed organization tenant ID parameter substitution, exposing enterprise customer data across tenants.',
        playbook: 'Emergency RLS Policy Enforcement & Customer Notification',
      },
      {
        id: 'INC-SAAS-002',
        title: 'Cloud Account Compromise',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 4,
        dataSensitivity: 4,
        attackConfidence: 0.92,
        businessImpact: 5,
        affectedAssets: ['K8S-PROD-EKS-CLUSTER', 'CORE-GATEWAY-ENVOY'],
        affectedUsersList: ['platform_lead_sre', 'iam_security_architect', 'devops_build_bot'],
        attackTypes: ['AWS Root Role Abuse', 'CloudTrail Disablement'],
        mitreTechniques: ['T1078.004: Cloud Accounts', 'T1562.001: Disable or Modify Tools'],
        story: 'Compromised AWS admin access key used from unexpected foreign ASN to spin up rogue GPU instances and modify VPC peering tables.',
        playbook: 'IAM Credential Revocation & Cloud Incident Containment',
      },
      {
        id: 'INC-SAAS-003',
        title: 'Software Supply Chain Attack',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 5,
        dataSensitivity: 4,
        attackConfidence: 0.90,
        businessImpact: 5,
        affectedAssets: ['GITHUB-ACTIONS-RUNNER', 'CORE-GATEWAY-ENVOY'],
        affectedUsersList: ['devops_build_bot', 'platform_lead_sre', 'backend_api_dev', 'iam_security_architect'],
        attackTypes: ['Dependency Typosquatting', 'Build Pipeline Poisoning'],
        mitreTechniques: ['T1195.002: Third-Party Software Vulnerabilities', 'T1059: Command Execution'],
        story: 'Malicious npm dependency injected into main deployment pipeline via typosquatted package, beaconing environment secrets to external dropzone.',
        playbook: 'Kill CI Runners & Purge Artifact Repository Cache',
      },
      {
        id: 'INC-SAAS-004',
        title: 'Secrets Exposure',
        severity: 4,
        assetImportance: 4,
        affectedUsers: 3,
        dataSensitivity: 5,
        attackConfidence: 0.88,
        businessImpact: 4,
        affectedAssets: ['HASHICORP-VAULT-PROD'],
        affectedUsersList: ['iam_security_architect', 'platform_lead_sre', 'backend_api_dev'],
        attackTypes: ['Hardcoded API Key Leak', 'Vault Token Hijack'],
        mitreTechniques: ['T1552.001: Credentials in Files', 'T1555: Credentials from Password Stores'],
        story: 'Production Vault root-level signing key accidentally committed to public Git repository during developer debugging session.',
        playbook: 'Immediate Key Revocation & Vault Auto-Roll Rotation',
      },
      {
        id: 'INC-SAAS-005',
        title: 'API Authorization Bypass',
        severity: 4,
        assetImportance: 4,
        affectedUsers: 4,
        dataSensitivity: 4,
        attackConfidence: 0.90,
        businessImpact: 4,
        affectedAssets: ['CORE-GATEWAY-ENVOY'],
        affectedUsersList: ['backend_api_dev', 'platform_lead_sre', 'iam_security_architect'],
        attackTypes: ['BOLA/IDOR', 'JWT Signature Stripping'],
        mitreTechniques: ['T1190: Exploit Public-Facing Application', 'T1078: Valid Accounts'],
        story: 'Alg "none" JWT signature stripping bypass on enterprise administrative billing and license upgrade endpoint.',
        playbook: 'Envoy JWT Filter Strict Verification Hotfix',
      },
      {
        id: 'INC-SAAS-006',
        title: 'Cloud Data Exfiltration',
        severity: 4,
        assetImportance: 4,
        affectedUsers: 4,
        dataSensitivity: 5,
        attackConfidence: 0.85,
        businessImpact: 4,
        affectedAssets: ['AURORA-MULTITENANT-DB'],
        affectedUsersList: ['backend_api_dev', 'platform_lead_sre', 'iam_security_architect'],
        attackTypes: ['S3 Bucket Sync Leak', 'Mass Read Query'],
        mitreTechniques: ['T1530: Data from Cloud Storage', 'T1048: Exfiltration'],
        story: 'Adversary abusing compromised read-only service account to initiate cross-account S3 sync of 1.4 TB telemetry archive.',
        playbook: 'Apply S3 Bucket Block Public Access & VPC Endpoint Lockdown',
      },
    ],
  },
  government: {
    id: 'government',
    name: 'Government',
    description: 'Citizen data, critical infrastructure and national services',
    emphasis: [
      'Citizen Privacy',
      'Critical Infrastructure',
      'Nation-State Defense',
      'Confidential Enclaves',
      'Public Service Continuity',
    ],
    defaultVersion: 'weighted-v1-government',
    weights: {
      severity: 0.25,
      asset_importance: 0.20,
      affected_users: 0.15,
      data_sensitivity: 0.20,
      attack_confidence: 0.10,
      business_impact: 0.10,
    },
    threats: [
      {
        id: 'INC-GOV-001',
        title: 'Nation-State Intrusion',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 3,
        dataSensitivity: 5,
        attackConfidence: 0.95,
        businessImpact: 5,
        affectedAssets: ['CITIZEN-IDENTITY-CORE', 'GRID-SCADA-SUPERVISOR'],
        affectedUsersList: ['national_security_officer', 'registry_director', 'public_portal_admin'],
        attackTypes: ['Advanced Persistent Threat (APT)', 'Zero-Day Exploitation'],
        mitreTechniques: ['T1190: Exploit Public-Facing Application', 'T1021: Remote Services'],
        story: 'Sophisticated state-sponsored actor (APT-41 equivalent) exploiting zero-day vulnerability in edge VPN router to establish persistent lateral persistence.',
        playbook: 'National Threat Emergency Response & Classified Enclave Quarantine',
      },
      {
        id: 'INC-GOV-002',
        title: 'Critical Infrastructure Attack',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 5,
        dataSensitivity: 4,
        attackConfidence: 0.90,
        businessImpact: 5,
        affectedAssets: ['GRID-SCADA-SUPERVISOR'],
        affectedUsersList: ['national_security_officer', 'registry_director'],
        attackTypes: ['SCADA Protocol Tampering', 'Substation Controller Overload'],
        mitreTechniques: ['T0831: Manipulation of Control', 'T0855: Unauthorized Command Message'],
        story: 'Anomalous DNP3 control commands sent to power distribution substation controllers, threatening regional electrical grid brownouts.',
        playbook: 'Switch SCADA Network to Isolated Island Mode',
      },
      {
        id: 'INC-GOV-003',
        title: 'Citizen Data Breach',
        severity: 4,
        assetImportance: 4,
        affectedUsers: 5,
        dataSensitivity: 5,
        attackConfidence: 0.88,
        businessImpact: 4,
        affectedAssets: ['CITIZEN-IDENTITY-CORE', 'REVENUE-TAX-FILING'],
        affectedUsersList: ['registry_director', 'public_portal_admin', 'national_security_officer'],
        attackTypes: ['Bulk SSN Exfiltration', 'Privilege Escalation'],
        mitreTechniques: ['T1005: Data from Local System', 'T1048: Exfiltration'],
        story: 'Unauthorized dump of 1.2 million citizen social security identifiers and tax filings staged through encrypted external FTP channel.',
        playbook: 'Revoke Civilian Database Credentials & Launch Forensic Audit',
      },
      {
        id: 'INC-GOV-004',
        title: 'Sensitive Document Exfiltration',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 2,
        dataSensitivity: 5,
        attackConfidence: 0.90,
        businessImpact: 4,
        affectedAssets: ['CITIZEN-IDENTITY-CORE'],
        affectedUsersList: ['national_security_officer', 'registry_director'],
        attackTypes: ['Classified Briefing Exfil', 'USB Rubber Ducky Device'],
        mitreTechniques: ['T1052: Exfiltration Over Physical Medium', 'T1025: Data from Removable Media'],
        story: 'Physical rogue HID implant detected on secure terminal in high-clearance ministry conference wing copying policy whitepapers.',
        playbook: 'Physical Terminal Air-Gapping & Security Countermeasure Scans',
      },
      {
        id: 'INC-GOV-005',
        title: 'Government Portal Attack',
        severity: 4,
        assetImportance: 4,
        affectedUsers: 5,
        dataSensitivity: 3,
        attackConfidence: 0.85,
        businessImpact: 4,
        affectedAssets: ['GOV-SERVICES-GATEWAY'],
        affectedUsersList: ['public_portal_admin', 'registry_director'],
        attackTypes: ['DDoS Attack', 'Defacement Attempt'],
        mitreTechniques: ['T1498: Network Denial of Service', 'T1491: Defacement'],
        story: 'Massive terabit volumetric DDoS paired with SQL injection attempts targeting voter registration and social welfare portals.',
        playbook: 'National Cyber Defense Perimeter Shield Activation',
      },
      {
        id: 'INC-GOV-006',
        title: 'Credential Compromise',
        severity: 3,
        assetImportance: 4,
        affectedUsers: 4,
        dataSensitivity: 4,
        attackConfidence: 0.80,
        businessImpact: 3,
        affectedAssets: ['REVENUE-TAX-FILING'],
        affectedUsersList: ['public_portal_admin', 'registry_director', 'national_security_officer'],
        attackTypes: ['Staff Credential Compromise', 'Shadow IT'],
        mitreTechniques: ['T1078: Valid Accounts'],
        story: 'Department staff credentials compromised via unauthorized third-party file sharing tool installed on administrative laptop.',
        playbook: 'Disable Account Active Directory Profile & Re-Image Asset',
      },
    ],
  },
  education: {
    id: 'education',
    name: 'Education',
    description: 'Student privacy, campus systems, research data and academic accounts',
    emphasis: [
      'Student Records (FERPA)',
      'Learning Platforms',
      'Campus Networks',
      'Grant-Funded Research',
      'Faculty Accounts',
    ],
    defaultVersion: 'weighted-v1-education',
    weights: {
      severity: 0.20,
      asset_importance: 0.15,
      affected_users: 0.20,
      data_sensitivity: 0.20,
      attack_confidence: 0.10,
      business_impact: 0.15,
    },
    threats: [
      {
        id: 'INC-EDU-001',
        title: 'University Ransomware',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 5,
        dataSensitivity: 4,
        attackConfidence: 0.95,
        businessImpact: 5,
        affectedAssets: ['STUDENT-INFO-SYSTEM', 'CANVAS-LMS-HOST01'],
        affectedUsersList: ['registrar_director', 'prof_hawking_pi', 'student_affairs_admin', 'campus_network_eng'],
        attackTypes: ['Campus Ransomware', 'Backup Deletion'],
        mitreTechniques: ['T1486: Data Encrypted for Impact', 'T1490: Inhibit System Recovery'],
        story: 'Double-extortion ransomware encrypting student record databases and threatening publication of financial aid information before finals week.',
        playbook: 'Isolate Academic Network Subnets & Restore Air-Gapped Tapes',
      },
      {
        id: 'INC-EDU-002',
        title: 'Research Data Theft',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 2,
        dataSensitivity: 5,
        attackConfidence: 0.90,
        businessImpact: 4,
        affectedAssets: ['QUANTUM-RESEARCH-GRID'],
        affectedUsersList: ['prof_hawking_pi', 'registrar_director'],
        attackTypes: ['IP Exfiltration', 'Foreign Intelligence Targeting'],
        mitreTechniques: ['T1005: Data from Local System', 'T1048: Exfiltration'],
        story: 'Covert exfiltration of proprietary quantum algorithm research data funded by national defense grants to a foreign university mirror.',
        playbook: 'Air-Gap HPC Cluster & Notify Federal Grant Compliance',
      },
      {
        id: 'INC-EDU-003',
        title: 'Student Data Breach',
        severity: 4,
        assetImportance: 3,
        affectedUsers: 5,
        dataSensitivity: 5,
        attackConfidence: 0.88,
        businessImpact: 4,
        affectedAssets: ['STUDENT-INFO-SYSTEM'],
        affectedUsersList: ['registrar_director', 'student_affairs_admin', 'prof_hawking_pi', 'campus_network_eng'],
        attackTypes: ['FERPA Breach', 'SQL Injection'],
        mitreTechniques: ['T1190: Exploit Public-Facing Application', 'T1005: Data from Local System'],
        story: 'SQL injection in student transcript request form leading to disclosure of 42,000 student grades, birth dates, and tuition payment cards.',
        playbook: 'FERPA Disclosure Protocol & WAF Virtual Patching',
      },
      {
        id: 'INC-EDU-004',
        title: 'Learning Management System Attack',
        severity: 4,
        assetImportance: 4,
        affectedUsers: 5,
        dataSensitivity: 3,
        attackConfidence: 0.85,
        businessImpact: 4,
        affectedAssets: ['CANVAS-LMS-HOST01'],
        affectedUsersList: ['student_affairs_admin', 'prof_hawking_pi', 'registrar_director', 'campus_network_eng'],
        attackTypes: ['Grade Tampering', 'Privilege Escalation'],
        mitreTechniques: ['T1068: Privilege Escalation', 'T1565: Data Manipulation'],
        story: 'Unauthorized grade modification script elevating course test scores across undergraduate computer science curriculum.',
        playbook: 'Roll Back Gradebook Logs & Enforce Faculty FIDO2 MFA',
      },
      {
        id: 'INC-EDU-005',
        title: 'Campus Network Compromise',
        severity: 4,
        assetImportance: 4,
        affectedUsers: 5,
        dataSensitivity: 3,
        attackConfidence: 0.80,
        businessImpact: 3,
        affectedAssets: ['CAMPUS-WIFI-CONTROLLER'],
        affectedUsersList: ['campus_network_eng', 'student_affairs_admin', 'registrar_director'],
        attackTypes: ['Rogue AP', 'DNS Hijacking'],
        mitreTechniques: ['T1557: Adversary-in-the-Middle', 'T1071: Standard Protocol'],
        story: 'Evil twin wireless access points deployed across student union cafeteria intercepting unencrypted institutional credentials.',
        playbook: 'Wireless Intrusion Prevention Rogue AP Triangulation',
      },
      {
        id: 'INC-EDU-006',
        title: 'Faculty Account Takeover',
        severity: 3,
        assetImportance: 3,
        affectedUsers: 3,
        dataSensitivity: 4,
        attackConfidence: 0.82,
        businessImpact: 3,
        affectedAssets: ['CANVAS-LMS-HOST01'],
        affectedUsersList: ['prof_hawking_pi', 'registrar_director', 'student_affairs_admin'],
        attackTypes: ['Phished Faculty Credentials', 'Exam Leak'],
        mitreTechniques: ['T1566: Phishing', 'T1078: Valid Accounts'],
        story: 'Phished departmental faculty credentials used to access upcoming final exam question banks and distribution keys.',
        playbook: 'Reset Department Account Sessions & Re-Issue Examination Papers',
      },
    ],
  },
  manufacturing: {
    id: 'manufacturing',
    name: 'Manufacturing',
    description: 'OT/ICS, SCADA, production continuity and industrial safety',
    emphasis: [
      'Operational Technology (OT)',
      'SCADA / ICS Systems',
      'Assembly Line Safety',
      'Industrial Control Networks',
      'Downtime Prevention',
    ],
    defaultVersion: 'weighted-v1-manufacturing',
    weights: {
      severity: 0.25,
      asset_importance: 0.20,
      affected_users: 0.10,
      data_sensitivity: 0.10,
      attack_confidence: 0.15,
      business_impact: 0.20,
    },
    threats: [
      {
        id: 'INC-MFG-001',
        title: 'OT/ICS Compromise',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 2,
        dataSensitivity: 3,
        attackConfidence: 0.95,
        businessImpact: 5,
        affectedAssets: ['SCADA-PLANT-MASTER', 'SIEMENS-S7-PLC-RACK'],
        affectedUsersList: ['lead_ot_engineer', 'plant_operations_dir'],
        attackTypes: ['PLC Logic Injection', 'Safety System Overwrite'],
        mitreTechniques: ['T0831: Manipulation of Control', 'T0855: Unauthorized Command'],
        story: 'Malicious engineering workstation reprogramming safety-instrumented system (SIS) thresholds on heavy industrial hydraulic presses.',
        playbook: 'OT Safety Interlock Trip & Emergency Plant Floor Scram',
      },
      {
        id: 'INC-MFG-002',
        title: 'Production Line Disruption',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 2,
        dataSensitivity: 2,
        attackConfidence: 0.92,
        businessImpact: 5,
        affectedAssets: ['SCADA-PLANT-MASTER', 'MES-DISPATCH-SERVER'],
        affectedUsersList: ['lead_ot_engineer', 'plant_operations_dir'],
        attackTypes: ['Robotic Cell Stoppage', 'Modbus Protocol Flood'],
        mitreTechniques: ['T0814: Denial of Service', 'T0804: Block Reporting'],
        story: 'Modbus TCP flood saturating assembly line conveyor bus, stalling $2.4M/hour automotive chassis welding operations.',
        playbook: 'Reboot Automation Switch & Switch to Offline Staging Buffer',
      },
      {
        id: 'INC-MFG-003',
        title: 'Industrial Ransomware',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 3,
        dataSensitivity: 3,
        attackConfidence: 0.94,
        businessImpact: 5,
        affectedAssets: ['MES-DISPATCH-SERVER', 'DESIGN-CAD-VAULT'],
        affectedUsersList: ['plant_operations_dir', 'lead_ot_engineer', 'cad_patent_designer'],
        attackTypes: ['OT Historian Encryption', 'Factory Floor Lockout'],
        mitreTechniques: ['T1486: Data Encrypted for Impact', 'T1489: Service Stop'],
        story: 'Targeted manufacturing ransomware (EKANS variant) terminating industrial processes and encrypting manufacturing execution system dispatchers.',
        playbook: 'Sever Purdue Model Level 3/2 Boundary Firewall',
      },
      {
        id: 'INC-MFG-004',
        title: 'SCADA Attack',
        severity: 5,
        assetImportance: 5,
        affectedUsers: 1,
        dataSensitivity: 2,
        attackConfidence: 0.90,
        businessImpact: 5,
        affectedAssets: ['SCADA-PLANT-MASTER'],
        affectedUsersList: ['lead_ot_engineer'],
        attackTypes: ['HMI Screen Hijacking', 'False Sensor Telemetry'],
        mitreTechniques: ['T0836: Modify Parameter', 'T0856: Spoof Reporting'],
        story: 'Rogue technician laptop spoofing thermocouple telemetry readings to HMI operators while heating chemical smelting reactors beyond tolerance.',
        playbook: 'Manual Pressure Relief Valve Activation & Air-Gap Controller',
      },
      {
        id: 'INC-MFG-005',
        title: 'Intellectual Property Theft',
        severity: 4,
        assetImportance: 4,
        affectedUsers: 2,
        dataSensitivity: 5,
        attackConfidence: 0.88,
        businessImpact: 4,
        affectedAssets: ['DESIGN-CAD-VAULT'],
        affectedUsersList: ['cad_patent_designer', 'lead_ot_engineer'],
        attackTypes: ['Blueprints Exfiltration', 'Proprietary CAD Theft'],
        mitreTechniques: ['T1005: Data from Local System', 'T1048: Exfiltration'],
        story: 'Uncompressed export of 3D CAD turbine blade schematics and metallurgical stress test data transferred to foreign adversary server.',
        playbook: 'Quarantine Engineering Vault & Restrict Outbound USB Access',
      },
      {
        id: 'INC-MFG-006',
        title: 'Supplier Network Compromise',
        severity: 4,
        assetImportance: 4,
        affectedUsers: 3,
        dataSensitivity: 3,
        attackConfidence: 0.85,
        businessImpact: 4,
        affectedAssets: ['SUPPLIER-EDI-PORTAL'],
        affectedUsersList: ['supplier_coordinator', 'plant_operations_dir', 'lead_ot_engineer'],
        attackTypes: ['Supply Chain Portal Abuse', 'Poisoned Purchase Orders'],
        mitreTechniques: ['T1199: Trusted Relationship', 'T1078: Valid Accounts'],
        story: 'Compromised supplier credential injected fraudulent raw titanium consignment orders, threatening production delivery timeline.',
        playbook: 'Disable Supplier EDI API Keys & Perform Out-of-Band Verification',
      },
    ],
  },
};

/**
 * 6-Factor Calculation Engine Implementation (compatible with backend).
 * Formula:
 *   Normalized Factor Value (0-100) * Factor Weight
 * Sum of all 6 factor contributions gives final score.
 */
export function calculateFactorContributions(
  threat: ThreatDefinition,
  weights: SectorWeights,
  batchMaxUsers = 5
): Record<string, { factor_name: string; raw_value: string; normalized_value: number; weight: number; contribution: number }> {
  // 1. Normalization
  const normSev = (threat.severity / 5.0) * 100.0;
  const normAsset = (threat.assetImportance / 5.0) * 100.0;
  const normUsers = Math.min(100.0, (threat.affectedUsers / batchMaxUsers) * 100.0);
  const normData = (threat.dataSensitivity / 5.0) * 100.0;
  const normConf = Math.min(100.0, Math.max(0.0, threat.attackConfidence * 100.0));
  const normImpact = (threat.businessImpact / 5.0) * 100.0;

  // 2. Contributions
  const cSev = normSev * weights.severity;
  const cAsset = normAsset * weights.asset_importance;
  const cUsers = normUsers * weights.affected_users;
  const cData = normData * weights.data_sensitivity;
  const cConf = normConf * weights.attack_confidence;
  const cImpact = normImpact * weights.business_impact;

  return {
    Severity: {
      factor_name: 'Severity',
      raw_value: `${threat.severity}/5`,
      normalized_value: normSev,
      weight: weights.severity,
      contribution: Number(cSev.toFixed(2)),
    },
    'Asset Importance': {
      factor_name: 'Asset Importance',
      raw_value: `${threat.assetImportance}/5 (TIER ${threat.assetImportance >= 5 ? 1 : 2})`,
      normalized_value: normAsset,
      weight: weights.asset_importance,
      contribution: Number(cAsset.toFixed(2)),
    },
    'Affected Users': {
      factor_name: 'Affected Users',
      raw_value: `${threat.affectedUsers} User(s)`,
      normalized_value: normUsers,
      weight: weights.affected_users,
      contribution: Number(cUsers.toFixed(2)),
    },
    'Data Sensitivity': {
      factor_name: 'Data Sensitivity',
      raw_value: `${threat.dataSensitivity}/5`,
      normalized_value: normData,
      weight: weights.data_sensitivity,
      contribution: Number(cData.toFixed(2)),
    },
    'Attack Confidence': {
      factor_name: 'Attack Confidence',
      raw_value: `${Math.round(threat.attackConfidence * 100)}%`,
      normalized_value: normConf,
      weight: weights.attack_confidence,
      contribution: Number(cConf.toFixed(2)),
    },
    'Business Impact': {
      factor_name: 'Business Impact',
      raw_value: `${threat.businessImpact}/5`,
      normalized_value: normImpact,
      weight: weights.business_impact,
      contribution: Number(cImpact.toFixed(2)),
    },
  };
}

export function calculateThreatScore(threat: ThreatDefinition, weights: SectorWeights, batchMaxUsers = 5): number {
  const contribs = calculateFactorContributions(threat, weights, batchMaxUsers);
  const total = Object.values(contribs).reduce((sum, item) => sum + item.contribution, 0);
  return Number(Math.min(100.0, Math.max(0.0, total)).toFixed(2));
}

export function calculateContextualRiskIndex(threats: ThreatDefinition[], weights: SectorWeights): number {
  if (!threats || threats.length === 0) return 0;
  const maxUsers = Math.max(...threats.map((t) => t.affectedUsers), 1);
  const scores = threats.map((t) => calculateThreatScore(t, weights, maxUsers));
  const avg = scores.reduce((sum, s) => sum + s, 0) / scores.length;
  return Number(avg.toFixed(1));
}

export function getSectorProfile(sectorId: string): SectorProfile {
  const key = sectorId?.toLowerCase() || 'healthcare';
  return SECTOR_PROFILES[key] || SECTOR_PROFILES.healthcare;
}

export function getSectorThreats(sectorId: string): ThreatDefinition[] {
  return getSectorProfile(sectorId).threats;
}

export function getPrimaryAsset(profile: SectorProfile): string {
  if (profile.threats && profile.threats.length > 0 && profile.threats[0].affectedAssets?.length > 0) {
    return profile.threats[0].affectedAssets[0];
  }
  return 'CORE-ASSET-01';
}

export function getPrimaryUser(profile: SectorProfile): string {
  if (profile.threats && profile.threats.length > 0 && profile.threats[0].affectedUsersList?.length > 0) {
    return profile.threats[0].affectedUsersList[0];
  }
  return 'sec_admin';
}
